basePath: /
host: localhost:1323
info:
  contact: {}
  title: Hello World
paths:
  /goodbye:
    get:
      responses: {}
      tags:
      - Goodbye
  /hello:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      tags:
      - Hello
swagger: "2.0"
